### PR TITLE
bump illuminate/support

### PR DESCRIPTION
**Pull request by simonbuehler**
bump for L9

### CODE REVIEW

**Comment by Gummibeer** [comment]
Testbench and GitHub Workflow Matrix are missing.

**Comment by simonbuehler** [comment]
ok, have to read this up

**Comment by simonbuehler** [comment]
should be fixed

**Comment by simonbuehler** [comment]
can this be merged?

**Comment by mstaack** [comment]
@Gummibeer can you have a look? thanks mate

**Review by Gummibeer — APPROVED** [review]

**Pull request merged**
